podTemplate(
  cloud: 'kubernetes',
  namespace: 'jenkins',
  activeDeadlineSeconds: '300',
  showRawYaml: 'false',
  containers: [
  containerTemplate(
    name: 'centos',
    image: 'centos:latest',
    ttyEnabled: true,
    command: 'cat'
  )
]) {
  node(POD_LABEL) {
      try {
        // project variables
        def project_directory = "${WORKSPACE}/go/web"

/*
          stage("Get Golang Project") {
            git url: 'https://github.com/Condoamanti/programming.git'
          } // stage end
*/
          container('centos') {
            stage('Download Docker Dependencies') {
              sh """
              rm -rf /etc/yum.repos.d/*

              echo \"[artifactory-centos-8]
name=artifactory-centos-8-baseos
baseurl=http://admin:AP72goB1ugbhNixgk4oZQD1JSMK@k8snode1dc1.jittersolutions.com:32382/artifactory/rpm/8/BaseOS/x86_64/os
enabled=1
gpgcheck=0

[artifactory-centos-8-extras]
name=artifactory-centos-8-os
baseurl=http://admin:AP72goB1ugbhNixgk4oZQD1JSMK@k8snode1dc1.jittersolutions.com:32382/artifactory/rpm/8/extras/x86_64/os
enabled=1
gpgcheck=0

[artifactory-centos-8-cr]
name=artifactory-centos-8-os
baseurl=http://admin:AP72goB1ugbhNixgk4oZQD1JSMK@k8snode1dc1.jittersolutions.com:32382/artifactory/rpm/8/cr/x86_64/os
enabled=1
gpgcheck=0\" >> /etc/yum.repos.d/artifactory.repo

              yum update -y

              yum install epel-release
              """
            } // stage end
          } // container end
      } catch (err) {
        echo "Caught: ${err}"
        currentBuild.result = 'FAILURE'
      } finally {
    }
  } // node end
} // podTemplate end