podTemplate(
  cloud: 'kubernetes',
  namespace: 'jenkins',
  activeDeadlineSeconds: '300',
  showRawYaml: 'false',
  containers: [
  containerTemplate(
    name: 'centos',
    image: 'centos:latest',
    ttyEnabled: true,
    command: 'cat'
  )
]) {
  node(POD_LABEL) {
      try {
        // project variables
        def project_directory = "${WORKSPACE}/go/web"

/*
          stage("Get Golang Project") {
            git url: 'https://github.com/Condoamanti/programming.git'
          } // stage end
*/
          container('centos') {
            stage('Download Docker Dependencies') {
              sh """
              mkdir /etc/yum.repos.d/disabled
              cp -af !(disabled) /etc/yum.repos.d/* /etc/yum.repos.d/disabled
              rm -rf !(disabled) /etc/yum.repos.d/*
              
              echo \"[Artifactory]
              name=Artifactory
              baseurl=http://admin:AP3kqbPPh1VqC1oA6ZuqoBnzyfW@k8snode1dc1.jittersolutions.com:32382/artifactory/rpm-remote/<PATH_TO_REPODATA_FOLDER>
              enabled=1
              gpgcheck=0\" >> /etc/yum.repos.d/artifactory.repo

              cat /etc/yum.repos.d/artifactory.repo
              ls /etc/yum.repos.d/
              """
            } // stage end
          } // container end
      } catch (err) {
        echo "Caught: ${err}"
        currentBuild.result = 'FAILURE'
      } finally {
    }
  } // node end
} // podTemplate end