podTemplate(
  cloud: 'kubernetes',
  namespace: 'jenkins',
  activeDeadlineSeconds: '300',
  showRawYaml: 'false',
  containers: [
  containerTemplate(
    name: 'ubuntu',
    image: 'ubuntu:latest',
    ttyEnabled: true,
    command: 'cat'
  )
]) {
  node(POD_LABEL) {
      try {
        // project variables
        def project_directory = "${WORKSPACE}/go/web"

/*
          stage("Get Golang Project") {
            git url: 'https://github.com/Condoamanti/programming.git'
          } // stage end
*/
          container('ubuntu') {
            stage('Download Docker Dependencies') {
              sh """
              apt-get update -y

              echo 'installing curl'
              apt-get install curl -y

              echo 'installing gnupg2'
              apt-get install gnupg2 -y

              echo 'downloading docker gpg key'
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

              echo 'adding docker repository'
              apt-get install software-properties-common -y
              add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable\"
              
              apt-get update -y

              echo 'installing docker-ce'
              apt-get install docker-ce -y
              
              echo 'installing docker-ce-cli'
              apt-get docker-ce-cli -y
              
              echo 'installing containerd.io'
              apt-get containerd.io -y

              systemctl status docker
              """
            } // stage end
          } // container end
      } catch (err) {
        echo "Caught: ${err}"
        currentBuild.result = 'FAILURE'
      } finally {
    }
  } // node end
} // podTemplate end