if ("${project_name}" != "") {
  println("project_name: ${project_name}")

  podTemplate(
    cloud: 'kubernetes',
    namespace: 'jenkins',
    activeDeadlineSeconds: '100',
    showRawYaml: 'false',
    containers: [
    containerTemplate(
      name: 'golang',
      image: 'golang:latest',
      ttyEnabled: true,
      command: 'cat'
    )
  ]) {
    node(POD_LABEL) {
        try {
          // project variables
          def project_directory = "${WORKSPACE}/go/examples"
          if (fileExists "${project_directory}/${project_name}.go") {

            stage("Get Golang Project") {
              git url: 'https://github.com/Condoamanti/programming.git'
            } // stage end

            container('golang') {
              stage('Build Golang Project') {
                sh """
                cd ${project_directory};
                go run ${project_name}.go;
                """
              } // stage end
            } // container end
          } // if end
        } catch (err) {
          echo "Caught: ${err}"
          currentBuild.result = 'FAILURE'
        } finally {
      }
    } // node end
  } // podTemplate end
} else {
  println("variable [project_name] is undefined, current value is [${project_name}]")
} // else end