podTemplate(
  cloud: 'kubernetes',
  namespace: 'jenkins',
  activeDeadlineSeconds: '100',
  showRawYaml: 'false',
  containers: [
  containerTemplate(
    name: 'golang',
    image: 'golang:latest',
    ttyEnabled: true,
    command: 'cat'
  )
]) {

  node(POD_LABEL) {

    stage("Get Golang Project") {
      //git url: 'https://github.com/hashicorp/terraform.git'
      println("here1")
      container('golang') {
        stage('Build DotNet Project') {
          /*
          sh """
          mkdir -p /go/src/github.com/hashicorp
          ln -s `pwd` /go/src/github.com/hashicorp/terraform
          cd /go/src/github.com/hashicorp/terraform && make core-dev
          """
          */
        }
      }
    }

  }
}
