podTemplate(
  cloud: 'kubernetes',
  namespace: 'jenkins',
  activeDeadlineSeconds: '100',
  showRawYaml: 'false',
  containers: [
  containerTemplate(
    name: 'golang',
    image: 'golang:latest',
    ttyEnabled: true,
    command: 'cat'
  )
]) {

  node(POD_LABEL) {
    try {
      container('golang') {

        stage("Get Golang Project") {
          git url: 'https://github.com/Condoamanti/programming.git'
        }

        stage('Build Golang Project') {
          sh """
          cd ${WORKSPACE}/go/hello_world;
          ls;
          pwd;
          go run ./hello-world.go;
          go build ./hello-world.go;
          ls;
          ./hello-world;
          """
        }
      } // container end
    } catch (err) {
      echo "Caught: ${err}"
      currentBuild.result = 'FAILURE'
    } finally {
    }
  }
}
