podTemplate(
  cloud: 'kubernetes',
  namespace: 'jenkins',
  activeDeadlineSeconds: '100',
  showRawYaml: 'false',
  containers: [
  containerTemplate(
    name: 'golang',
    image: 'golang:latest',
    ttyEnabled: true,
    command: 'cat'
  )
]) {

  node(POD_LABEL) {
    stage("Get Golang Project") {
      steps {
        git url: 'https://github.com/Condoamanti/programming.git'
        
        container('golang') {
          stage('Build Golang Project') {
            dir('/home/jenkins/agent/workspace/programming/go/hello_world') {
              sh """
              ls;
              go run ./hello-world.go;
              go build ./hello-world.go;
              ls;
              ./hello-world;
              """
            }
          }
        }
      }
    }
  }
}
